/*******************************************************************************
 * File Name: project.h  
 * PSoC Creator 2.2 Component Pack 6
 *
 *  Description:
 *  This file is automatically generated by PSoC Creator and should not 
 *  be edited by hand.
 *
 *
 ********************************************************************************
 * Copyright 2008-2013, Cypress Semiconductor Corporation.  All rights reserved.
 * You may use this file only in accordance with the license, terms, conditions, 
 * disclaimers, and limitations in the end user license agreement accompanying 
 * the software package with which this file was provided.
 ********************************************************************************/

#include <cyfitter_cfg.h>
#include <cydevice.h>
#include <cydevice_trm.h>
#include <cyfitter.h>
#include <Cond_PWM_out_aliases.h>
#include <Cond_PWM_out.h>
#include <Clock_1.h>
#include <PWM_1.h>
#include <Sample_Hold_2.h>
#include <Comp_2.h>
#include <Sample_Hold_1.h>
#include <Cond_Vx_aliases.h>
#include <Cond_Vx.h>
#include <Temp_Vout_aliases.h>
#include <Temp_Vout.h>
#include <ADC_DelSig_1.h>
#include <Cond_Vout_aliases.h>
#include <Cond_Vout.h>
#include <Sample_Hold_3.h>
#include <Cond_Vs_aliases.h>
#include <Cond_Vs.h>
#include <AMux_1.h>
#include <Temp_Vs_aliases.h>
#include <Temp_Vs.h>
#include <Temp_Vx_aliases.h>
#include <Temp_Vx.h>
#include <Comp_1.h>
#include <Comp_3.h>
#include <PWM_2.h>
#include <ADC_DelSig_1_theACLK.h>
#include <ADC_DelSig_1_Ext_CP_Clk.h>
#include <core_cm3_psoc5.h>
#include <core_cm3.h>
#include <CyDmac.h>
#include <CyFlash.h>
#include <CyLib.h>
#include <cypins.h>
#include <cyPm.h>
#include <CySpc.h>
#include <cytypes.h>

/*[]*/

