/*******************************************************************************
* File Name: project.h
* 
* PSoC Creator  3.3 SP1
*
* Description:
* It contains references to all generated header files and should not be modified.
* This file is automatically generated by PSoC Creator.
*
********************************************************************************
* Copyright (c) 2007-2015 Cypress Semiconductor.  All rights reserved.
* You may use this file only in accordance with the license, terms, conditions, 
* disclaimers, and limitations in the end user license agreement accompanying 
* the software package with which this file was provided.
********************************************************************************/

#include "cyfitter_cfg.h"
#include "cydevice.h"
#include "cydevice_trm.h"
#include "cyfitter.h"
#include "cydisabledsheets.h"
#include "AMux.h"
#include "ADC_DelSig_1.h"
#include "VWC_1_aliases.h"
#include "VWC_1.h"
#include "VWC_3_aliases.h"
#include "VWC_3.h"
#include "VWC_4_aliases.h"
#include "VWC_4.h"
#include "VWC_2_aliases.h"
#include "VWC_2.h"
#include "Power_VWC_1_aliases.h"
#include "Power_VWC_1.h"
#include "Power_Reg.h"
#include "Power_VWC_2_aliases.h"
#include "Power_VWC_2.h"
#include "Power_VWC_3_aliases.h"
#include "Power_VWC_3.h"
#include "Power_VWC_4_aliases.h"
#include "Power_VWC_4.h"
#include "ADC_DelSig_1_AMux.h"
#include "ADC_DelSig_1_Ext_CP_Clk.h"
#include "ADC_DelSig_1_IRQ.h"
#include "ADC_DelSig_1_theACLK.h"
#include "core_cm3_psoc5.h"
#include "core_cm3.h"
#include "CyDmac.h"
#include "CyFlash.h"
#include "CyLib.h"
#include "cypins.h"
#include "cyPm.h"
#include "CySpc.h"
#include "cytypes.h"
#include "core_cmFunc.h"
#include "core_cmInstr.h"

/*[]*/

