/*******************************************************************************
 * File Name: project.h  
 * PSoC Creator 2.2 Component Pack 6
 *
 *  Description:
 *  This file is automatically generated by PSoC Creator and should not 
 *  be edited by hand.
 *
 *
 ********************************************************************************
 * Copyright 2008-2013, Cypress Semiconductor Corporation.  All rights reserved.
 * You may use this file only in accordance with the license, terms, conditions, 
 * disclaimers, and limitations in the end user license agreement accompanying 
 * the software package with which this file was provided.
 ********************************************************************************/

#include <cyfitter_cfg.h>
#include <cydevice.h>
#include <cydevice_trm.h>
#include <cyfitter.h>
#include <Pin_1_aliases.h>
#include <Pin_1.h>
#include <Pin_2_aliases.h>
#include <Pin_2.h>
#include <Pin_3_aliases.h>
#include <Pin_3.h>
#include <Pin_4_aliases.h>
#include <Pin_4.h>
#include <Pin_5_aliases.h>
#include <Pin_5.h>
#include <Pin_6_aliases.h>
#include <Pin_6.h>
#include <Pin_7_aliases.h>
#include <Pin_7.h>
#include <Pin_8_aliases.h>
#include <Pin_8.h>
#include <Pin_9_aliases.h>
#include <Pin_9.h>
#include <int1_aliases.h>
#include <int1.h>
#include <inbt2_aliases.h>
#include <inbt2.h>
#include <crustal_aliases.h>
#include <crustal.h>
#include <I2C_1.h>
#include <I2C_1_PVT.h>
#include <Pin_14_aliases.h>
#include <Pin_14.h>
#include <Pin_15_aliases.h>
#include <Pin_15.h>
#include <isr_1.h>
#include <core_cm3_psoc5.h>
#include <core_cm3.h>
#include <CyDmac.h>
#include <CyFlash.h>
#include <CyLib.h>
#include <cypins.h>
#include <cyPm.h>
#include <CySpc.h>
#include <cytypes.h>

/*[]*/

