/*******************************************************************************
* File Name: project.h
* 
* PSoC Creator  3.3 SP1
*
* Description:
* It contains references to all generated header files and should not be modified.
* This file is automatically generated by PSoC Creator.
*
********************************************************************************
* Copyright (c) 2007-2015 Cypress Semiconductor.  All rights reserved.
* You may use this file only in accordance with the license, terms, conditions, 
* disclaimers, and limitations in the end user license agreement accompanying 
* the software package with which this file was provided.
********************************************************************************/

#include "cyfitter_cfg.h"
#include "cydevice.h"
#include "cydevice_trm.h"
#include "cyfitter.h"
#include "cydisabledsheets.h"
#include "LED_aliases.h"
#include "LED.h"
#include "Telit_PWR_aliases.h"
#include "Telit_PWR.h"
#include "Telit_RST_aliases.h"
#include "Telit_RST.h"
#include "Telit_ON_aliases.h"
#include "Telit_ON.h"
#include "Telit_UART.h"
#include "Telit_isr_rx.h"
#include "Telit_tx_aliases.h"
#include "Telit_tx.h"
#include "SleepTimer.h"
#include "sleep_isr.h"
#include "Telit_UART_IntClock.h"
#include "core_cm3_psoc5.h"
#include "core_cm3.h"
#include "CyDmac.h"
#include "CyFlash.h"
#include "CyLib.h"
#include "cypins.h"
#include "cyPm.h"
#include "CySpc.h"
#include "cytypes.h"
#include "core_cmFunc.h"
#include "core_cmInstr.h"

/*[]*/

