# THIS FILE IS AUTOMATICALLY GENERATED
# Project: C:\Users\karunmj\Documents\GitHub\m2m\hardware\psoc5\Campbell_Conductivity.cydsn\Campbell_Conductivity.cyprj
# Date: Tue, 24 Jun 2014 15:56:32 GMT
#set_units -time ns
create_clock -name {ADC_DelSig_1_Ext_CP_Clk(routed)} -period 83.333333333333329 -waveform {0 41.6666666666667} [list [get_pins {ClockBlock/dclk_0}]]
create_clock -name {CyIMO} -period 333.33333333333331 -waveform {0 166.666666666667} [list [get_pins {ClockBlock/imo}]]
create_clock -name {CyPLL_OUT} -period 41.666666666666664 -waveform {0 20.8333333333333} [list [get_pins {ClockBlock/pllout}]]
create_clock -name {CyILO} -period 1000000 -waveform {0 500000} [list [get_pins {ClockBlock/ilo}] [get_pins {ClockBlock/clk_100k}] [get_pins {ClockBlock/clk_1k}] [get_pins {ClockBlock/clk_32k}]]
create_clock -name {CyMASTER_CLK} -period 41.666666666666664 -waveform {0 20.8333333333333} [list [get_pins {ClockBlock/clk_sync}]]
create_generated_clock -name {ADC_DelSig_1_Ext_CP_Clk} -source [get_pins {ClockBlock/clk_sync}] -edges {1 3 5} [list [get_pins {ClockBlock/dclk_glb_0}]]
create_generated_clock -name {ADC_DelSig_1_theACLK} -source [get_pins {ClockBlock/clk_sync}] -edges {1 9 17} [list [get_pins {ClockBlock/aclk_glb_0}]]
create_clock -name {ADC_DelSig_1_theACLK(fixed-function)} -period 333.33333333333331 -waveform {0 166.666666666667} [get_pins {ClockBlock/aclk_glb_ff_0}]
create_generated_clock -name {Clock_1} -source [get_pins {ClockBlock/clk_sync}] -edges {1 113 241} [list [get_pins {ClockBlock/dclk_glb_1}]]
create_generated_clock -name {CyBUS_CLK} -source [get_pins {ClockBlock/clk_sync}] -edges {1 2 3} [list [get_pins {ClockBlock/clk_bus_glb}]]

set_false_path -from [get_pins {__ONE__/q}]

# Component constraints for C:\Users\karunmj\Documents\GitHub\m2m\hardware\psoc5\Campbell_Conductivity.cydsn\TopDesign\TopDesign.cysch
# Project: C:\Users\karunmj\Documents\GitHub\m2m\hardware\psoc5\Campbell_Conductivity.cydsn\Campbell_Conductivity.cyprj
# Date: Tue, 24 Jun 2014 15:56:16 GMT
