/*******************************************************************************
 * File Name: project.h
 * PSoC Creator  3.1 Component Pack 1
 *
 *  Description:
 *  This file is automatically generated by PSoC Creator and should not 
 *  be edited by hand.
 *
 *
 ********************************************************************************
 * Copyright 2008-2013, Cypress Semiconductor Corporation.  All rights reserved.
 * You may use this file only in accordance with the license, terms, conditions, 
 * disclaimers, and limitations in the end user license agreement accompanying 
 * the software package with which this file was provided.
 ********************************************************************************/

#include <cyfitter_cfg.h>
#include <cydevice.h>
#include <cydevice_trm.h>
#include <cyfitter.h>
#include <cydisabledsheets.h>
#include <LED_aliases.h>
#include <LED.h>
#include <Telit_PWR_aliases.h>
#include <Telit_PWR.h>
#include <Pin1_aliases.h>
#include <Pin1.h>
#include <Pin2_aliases.h>
#include <Pin2.h>
#include <Pin4_aliases.h>
#include <Pin4.h>
#include <Pin5_aliases.h>
#include <Pin5.h>
#include <Ultrasonic_ON_aliases.h>
#include <Ultrasonic_ON.h>
#include <Pin9_aliases.h>
#include <Pin9.h>
#include <Pin10_aliases.h>
#include <Pin10.h>
#include <Pin11_aliases.h>
#include <Pin11.h>
#include <Pin12_aliases.h>
#include <Pin12.h>
#include <Pin14_aliases.h>
#include <Pin14.h>
#include <Pin15_aliases.h>
#include <Pin15.h>
#include <Pin17_aliases.h>
#include <Pin17.h>
#include <Pin18_aliases.h>
#include <Pin18.h>
#include <Pin19_aliases.h>
#include <Pin19.h>
#include <Pin20_aliases.h>
#include <Pin20.h>
#include <Telit_RST_aliases.h>
#include <Telit_RST.h>
#include <Telit_ON_aliases.h>
#include <Telit_ON.h>
#include <Pin24_aliases.h>
#include <Pin24.h>
#include <Pin25_aliases.h>
#include <Pin25.h>
#include <Pin26_aliases.h>
#include <Pin26.h>
#include <Pin27_aliases.h>
#include <Pin27.h>
#include <Pin29_aliases.h>
#include <Pin29.h>
#include <Pin30_aliases.h>
#include <Pin30.h>
#include <Pin31_aliases.h>
#include <Pin31.h>
#include <Pin33_aliases.h>
#include <Pin33.h>
#include <Pin34_aliases.h>
#include <Pin34.h>
#include <Pin35_aliases.h>
#include <Pin35.h>
#include <Pin37_aliases.h>
#include <Pin37.h>
#include <Pin38_aliases.h>
#include <Pin38.h>
#include <Pin39_aliases.h>
#include <Pin39.h>
#include <VBAT_READ_EN_aliases.h>
#include <VBAT_READ_EN.h>
#include <Telit_ControlReg.h>
#include <Telit_tx_aliases.h>
#include <Telit_tx.h>
#include <Telit_isr_rx.h>
#include <Telit_UART.h>
#include <sleep_isr.h>
#include <SleepTimer.h>
#include <uart_ultrasonic.h>
#include <isr_byte_ultrasonic_rx.h>
#include <Telit_UART_IntClock.h>
#include <uart_ultrasonic_IntClock.h>
#include <core_cm3_psoc5.h>
#include <core_cm3.h>
#include <CyDmac.h>
#include <CyFlash.h>
#include <CyLib.h>
#include <cypins.h>
#include <cyPm.h>
#include <CySpc.h>
#include <cytypes.h>
#include <core_cmFunc.h>
#include <core_cmInstr.h>

/*[]*/

